library(copula)
library(ggplot2)
library(gridExtra)
library(ppcor)
library(tidyverse)
library(VineCopula)

source('nonparanormal.R')
# Also source or define here the functions:
#   - simulateOutcomeSamples (or simulateMarginalOutcomeSamples / simulateConditionalOutcomeSamples)
#   - bootstrappedKendallTest
#   - bootstrappedCondIndTest_GCM
# (See the previous code snippets for their definitions.)

# ------------------------------------------------------------------
# Six Variable Vine Copula Specification
# ------------------------------------------------------------------

sampleSize <- 10000   # Generate 10,000 samples for this example
D <- 6

structureMatrix <- matrix(
  c(1, 6, 5, 4, 3, 2,
    0, 2, 6, 5, 4, 3,
    0, 0, 3, 6, 5, 4,
    0, 0, 0, 4, 6, 5,
    0, 0, 0, 0, 5, 6,
    0, 0, 0, 0, 0, 6), 
  ncol = D)

familyMatrix <- matrix(
  c(0, 0, 0, 0, 0, 3, 
    0, 0, 0, 0, 0, 3,
    0, 0, 0, 0, 0, 3,
    0, 0, 0, 0, 0, 3,
    0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0), 
  ncol = D)

clayton_dep <- 3
normal_corr <- 0.8

parameterMatrix <- matrix(
  c(0, 0, 0, 0, 0, clayton_dep, 
    0, 0, 0, 0, 0, clayton_dep,
    0, 0, 0, 0, 0, clayton_dep,
    0, 0, 0, 0, 0, clayton_dep,
    0, 0, 0, 0, 0, normal_corr,
    0, 0, 0, 0, 0, 0), 
  ncol = D)

# ------------------------------------------------------------------
# Generate 10,000 Samples from the Vine Copula
# ------------------------------------------------------------------

vineOutput <- simulateRVineData(structureMatrix, familyMatrix, parameterMatrix, sampleSize)
simulatedData <- vineOutput$simdata

# We assume the first D-1 columns are the covariates and the Dth column is the outcome.
covariate_data <- simulatedData[, 1:(D - 1)]
# Use the simulated uniform marginals as the conditional (marginal) covariate ranks.
marg_covariate_ranks <- covariate_data

# Define the topological order (here using your custom order) and vine correlation parameters.
topoOrder <- c(5, 1, 2, 3, 4)
vine_cor_params <- c(normal_corr, 0, 0, 0, 0)

# ------------------------------------------------------------------
# (i) Generate Outcome Rank Samples Using simulateMarginalOutcomeSamples
# ------------------------------------------------------------------

sampleResults <- simulateMarginalOutcomeSamples(covariate_data = covariate_data,
                                                marginal_covariate_ranks = marg_covariate_ranks,
                                                vine_cor_params = vine_cor_params,
                                                topoOrder = topoOrder)

# The outcome rank samples generated by conditioning on the covariates:
outcomeRankSamples <- as.vector(sampleResults$outcomeRankSamples)

# For illustration, plot a histogram of the generated outcome ranks.
p_outcome <- ggplot(data.frame(outcome = outcomeRankSamples), aes(x = outcome)) +
  geom_histogram(bins = 30, fill = "lightblue", colour = "black") +
  labs(title = "Histogram of Generated Outcome Rank Samples",
       x = "Outcome Rank (on [0,1])", y = "Frequency") +
  scale_x_continuous(limits = c(0, 1)) +
  theme_minimal()
print(p_outcome)

# ------------------------------------------------------------------
# (ii) Run the Bootstrapped Kendall's Tau Test on Two Chosen Variables
# ------------------------------------------------------------------
n_boot <- 200
sample_size <- 1000

# Define a custom theme to match the style in your second script.
custom_theme <- theme_minimal() +
  theme(
    plot.title = element_blank(),
    text = element_text(family = "Helvetica", size = 14),
    axis.title = element_text(face = "bold"),
    panel.grid.major = element_line(color = "white"),
    panel.grid.minor = element_line(color = "white"),
    panel.background = element_rect(fill = "white"),
    plot.background  = element_rect(fill = "white"),
    panel.border = element_blank()
  )

# Example: For a transformed version, we compute u4_5_np and u6_5_np using BiCopHfunc.
u4_5_np <- BiCopHfunc(marg_covariate_ranks[,4], marg_covariate_ranks[,5],
                      family = 3, par = clayton_dep)$hfunc2
u6_5_np <- BiCopHfunc(outcomeRankSamples, marg_covariate_ranks[,5],
                      family = 1, par = normal_corr)$hfunc2

# Run bootstrapped Kendall's Tau test.
p_values1 <- bootstrappedKendallTest(x = u4_5_np, y = u6_5_np, 
                                     n_boot = n_boot, sample_size = sample_size)

p_conditional <- ggplot(data.frame(p_value = p_values1), aes(x = p_value)) +
  geom_histogram(bins = 10, fill = "grey30", colour = "black") +
  labs(title = "Bootstrapped Kendall's Tau p-values\n(Covariate 4 vs Outcome via Covariate 5)",
       x = "p-value", y = "Frequency") +
  scale_x_continuous(limits = c(0, 1)) +
  custom_theme
print(p_conditional)
unif_p_cond <- ks.test(p_values1, "punif")
cat("KS test p-value for uniformity (conditional):", unif_p_cond$p.value, "\n")
ggsave("bootstrapped_kendall_outcome_vs_u4_cond_u5.png", plot = p_conditional, 
       path = "./plots", width = 6, height = 4, dpi = 300)

# Run bootstrapped Kendall's Tau test for marginal version.
p_values2 <- bootstrappedKendallTest(x = marg_covariate_ranks[,4], y = outcomeRankSamples, 
                                     n_boot = n_boot, sample_size = sample_size)
p_marginal <- ggplot(data.frame(p_value = p_values2), aes(x = p_value)) +
  geom_histogram(bins = 10, fill = "grey30", colour = "black") +
  labs(title = "Bootstrapped Kendall's Tau p-values\n(Covariate 4 vs Outcome)",
       x = "p-value", y = "Frequency") +
  scale_x_continuous(limits = c(-1e-1, 1)) +
  custom_theme
print(p_marginal)
unif_p_marg <- ks.test(p_values2, "punif")
cat("KS test p-value for uniformity (marginal):", unif_p_marg$p.value, "\n")
ggsave("bootstrapped_kendall_outcome_vs_u4_marginal.png", plot = p_marginal, 
       path = "./plots", width = 6, height = 4, dpi = 300)

print(unif_p_cond$p.value)
print(unif_p_marg$p.value)
