library(copula)
library(ggplot2)
library(gridExtra)
library(ppcor)
library(tidyverse)
library(VineCopula)

source('nonparanormal.R')
# Also source or define here the functions:
#   - simulateOutcomeSamples
#   - bootstrappedKendallTest
# (See the previous code snippets for their definitions.)

# ------------------------------------------------------------------
# Six Variable Vine Copula Specification
# ------------------------------------------------------------------

sampleSize <- 1000   # Generate 1000 samples for this example
D <- 6

structureMatrix <- matrix(
  c(1, 6, 5, 4, 3, 2,
    0, 2, 6, 5, 4, 3,
    0, 0, 3, 6, 5, 4,
    0, 0, 0, 4, 6, 5,
    0, 0, 0, 0, 5, 6,
    0, 0, 0, 0, 0, 6), 
  ncol = D)

familyMatrix <- matrix(
  c(0, 0, 0, 0, 0, 3, 
    0, 0, 0, 0, 0, 3,
    0, 0, 0, 0, 0, 3,
    0, 0, 0, 0, 0, 3,
    0, 0, 0, 0, 0, 1,
    0, 0, 0, 0, 0, 0), 
  ncol = D)

clayton_dep <- 3
normal_corr <- 0.8

parameterMatrix <- matrix(
  c(0, 0, 0, 0, 0, clayton_dep, 
    0, 0, 0, 0, 0, clayton_dep,
    0, 0, 0, 0, 0, clayton_dep,
    0, 0, 0, 0, 0, clayton_dep,
    0, 0, 0, 0, 0, normal_corr,
    0, 0, 0, 0, 0, 0), 
  ncol = D)

# ------------------------------------------------------------------
# Generate 1000 Samples from the Vine Copula
# ------------------------------------------------------------------

# The vine simulation returns a list with an RVM object and a matrix of simulated data.
vineOutput <- simulateRVineData(structureMatrix, familyMatrix, parameterMatrix, sampleSize)
simulatedData <- vineOutput$simdata

# We assume the first D-1 columns are the covariates and the Dth column is the outcome.
covariate_data <- simulatedData[, 1:(D - 1)]
# Since the vine simulation returns uniform [0,1] marginals, we can use these as our conditional covariate ranks.
marg_covariate_ranks <- covariate_data

# Define the topological order (here the natural order: 1,2,...,D) and set the vine correlation parameter.
topoOrder <- (D-1):1
vine_cor_params <- c(normal_corr,0,0,0,0,0)

# ------------------------------------------------------------------
# (i) Generate Outcome Rank Samples Using simulateOutcomeSamples
# ------------------------------------------------------------------

sampleResults <- simulateMarginalOutcomeSamples(covariate_data = covariate_data,
                                        marginal_covariate_ranks = marg_covariate_ranks,
                                        vine_cor_params = vine_cor_params,
                                        topoOrder = topoOrder)

# The outcome rank samples generated by conditioning on the covariates:
outcomeRankSamples <- as.vector(sampleResults$outcomeRankSamples)

# For illustration, plot a histogram of the generated outcome ranks:
ggplot(data.frame(outcome = outcomeRankSamples), aes(x = outcome)) +
  geom_histogram(bins = 30, fill = "lightblue", colour = "black") +
  labs(title = "Histogram of Generated Outcome Rank Samples",
       x = "Outcome Rank (on [0,1])", y = "Frequency") +
  theme_minimal()


# ------------------------------------------------------------------
# (ii) Run the Bootstrapped Kendall's Tau Test on Two Chosen Variables
# ------------------------------------------------------------------

u4_5_np <- BiCopHfunc(marg_covariate_ranks[,4], marg_covariate_ranks[,5], family=3, par=clayton_dep)$hfunc2
hist(u4_5_np)
emp_corr <- cor(qnorm(outcomeRankSamples), qnorm(marg_covariate_ranks[,5]))
u6_5_np <- BiCopHfunc(outcomeRankSamples, marg_covariate_ranks[,5], family=1, par=normal_corr)$hfunc2
hist(u6_5_np)

# For example, test independence between covariate 1 and covariate 2.
p_values <- bootstrappedKendallTest(x = u4_5_np, y = u6_5_np, n_boot = 1000, sample_size = 100)

# Plot a histogram of the bootstrapped p-values.
ggplot(data.frame(p_value = p_values), aes(x = p_value)) +
  geom_histogram(bins = 30, fill = "lightgreen", colour = "black") +
  labs(title = "Bootstrapped Kendall's Tau p-values (Covariate 1 vs Covariate 2)",
       x = "p-value", y = "Frequency") +
  theme_minimal()

