library(copula)
library(ggplot2)
library(gridExtra)
library(ppcor)
library(tidyverse)
library(VineCopula)

source('nonparanormal.R')
# Also source or define here the functions:
#   - simulateOutcomeSamples
#   - bootstrappedKendallTest
# (See the previous code snippets for their definitions.)

# ------------------------------------------------------------------
# Six Variable Vine Copula Specification
# ------------------------------------------------------------------

sampleSize <- 200   # Generate 1000 samples for this example
D <- 3
conditional_ranks <- matrix(runif(n=D*sampleSize), ncol = D)

# ------------------------------------------------------------------
# Generate 1000 Samples from the BN
# ------------------------------------------------------------------

# Step 1: Generate Z1 ~ Gamma(shape = 2, scale = 2)
U1 <- runif(sampleSize)
Z1 <- qnorm(U1, mean = 0, scale = 1)

# Step 2: Generate Z2 | Z1 ~ Gamma(shape = 2 + 3*Z1, scale = 1)
U2_1 <- runif(sampleSize)
Z2 <- qnorm(U2_1, mean = Z1, sd = 0.75)

# Step 3: Generate Z3 | Z1, Z2 ~ Gamma(shape = 2 + 3*(Z2/2), scale = 1)
U3_21 <- runif(sampleSize)
Z3 <- qnorm(U3_21, mean = Z2, sd = 0.75)

# Combine the samples into a data frame.
# The columns Z1, Z2, Z3 are the observational samples.
# The columns rank_Z1, rank_Z2, rank_Z3 are the underlying U(0,1) draws.
dataBN_norm <- data.frame(Z1 = Z1, Z2 = Z2, Z3 = Z3,
                           rank_Z1 = U1, rank_Z2 = U2_1, rank_Z3 = U3_21)

# We assume the first D-1 columns are the covariates and the Dth column is the outcome.
covariate_data <- dataBN_norm[, 1:D]
# Since the vine simulation returns uniform [0,1] marginals, we can use these as our conditional covariate ranks.
cond_covariate_ranks <- dataBN_norm[, (D+1):(2*D)]

# Define the topological order (here the natural order: 1,2,...,D) and set the vine correlation parameter.
topoOrder <- 1:D
vine_cor_params <- c(0.8, 0, 0.8)

# ------------------------------------------------------------------
# (i) Generate Outcome Rank Samples Using simulateOutcomeSamples
# ------------------------------------------------------------------

sampleResults <- simulateConditionalOutcomeSamples(covariate_data = covariate_data,
                                        cond_covariate_ranks = cond_covariate_ranks,
                                        vine_cor_params = vine_cor_params,
                                        topoOrder = topoOrder)

# The outcome rank samples generated by conditioning on the covariates:
outcomeRankSamples <- as.vector(sampleResults$outcomeRankSamples)

# For illustration, plot a histogram of the generated outcome ranks:
ggplot(data.frame(outcome = outcomeRankSamples), aes(x = outcome)) +
  geom_histogram(bins = 30, fill = "lightblue", colour = "black") +
  labs(title = "Histogram of Generated Outcome Rank Samples",
       x = "Outcome Rank (on [0,1])", y = "Frequency") +
  theme_minimal()


# ------------------------------------------------------------------
# (ii) Run the Bootstrapped Kendall's Tau Test on Two Chosen Variables
# ------------------------------------------------------------------

u4_5_np <- BiCopHfunc(marg_covariate_ranks[,4], marg_covariate_ranks[,5], family=3, par=clayton_dep)$hfunc2
hist(u4_5_np)
emp_corr <- cor(qnorm(outcomeRankSamples), qnorm(marg_covariate_ranks[,5]))
u6_5_np <- BiCopHfunc(outcomeRankSamples, marg_covariate_ranks[,5], family=1, par=normal_corr)$hfunc2
hist(u6_5_np)
test.results <- cor.test(F4_5_np, F6_5_np, method=c("kendall"))
test.results$p.value

# For example, test independence between covariate 1 and covariate 2.
p_values <- bootstrappedKendallTest(x = u4_5_np, y = u6_5_np, n_boot = 1000, sample_size = 100)

# Plot a histogram of the bootstrapped p-values.
ggplot(data.frame(p_value = p_values), aes(x = p_value)) +
  geom_histogram(bins = 30, fill = "lightgreen", colour = "black") +
  labs(title = "Bootstrapped Kendall's Tau p-values (Covariate 1 vs Covariate 2)",
       x = "p-value", y = "Frequency") +
  theme_minimal()



n <- 250
X <- rnorm(n)
Y <- rnorm(n)
# Let's assume Z is a matrix with two conditioning variables.
Z <- cbind(rnorm(n))

# Run the bootstrapped KCI test with a progress bar.
p_values <- bootstrappedKCI(X, Y, Z, n_boot = 100, sample_size = n)

# Plot a histogram of the bootstrapped p-values.
library(ggplot2)
ggplot(data.frame(p_value = p_values), aes(x = p_value)) +
  geom_histogram(bins = 15, fill = "lightgreen", colour = "black") +
  labs(title = "Bootstrapped KCI p-values", x = "p-value", y = "Frequency") +
  theme_minimal()

