library(CondIndTests)
library(copula)
library(GeneralisedCovarianceMeasure)
library(ggplot2)
library(gridExtra)
library(ppcor)
library(tidyverse)
library(VineCopula)

source('nonparanormal.R')
# Also source or define here the functions:
#   - simulateOutcomeSamples
#   - bootstrappedKendallTest
# (See the previous code snippets for their definitions.)

# ------------------------------------------------------------------
# Six Variable Vine Copula Specification
# ------------------------------------------------------------------

sampleSize <- 20000   # Generate 1000 samples for this example
D <- 3
conditional_ranks <- matrix(runif(n=D*sampleSize), ncol = D)

# ------------------------------------------------------------------
# Generate 1000 Samples from the BN
# ------------------------------------------------------------------

# Step 1: Generate Z1 ~ Gamma(shape = 2, scale = 2)
U1 <- runif(sampleSize)
# Z1 <- qnorm(U1, mean = 0, sd = 1)
Z1 <- qgamma(U1, shape = 2, scale = 2)

# Step 2: Generate Z2 | Z1 ~ Gamma(shape = 2 + 3*Z1, scale = 1)
U2_1 <- runif(sampleSize)
# Z2 <- qnorm(U2_1, mean = Z1, sd = 0.75)
Z2 <- qgamma(U2_1, shape = 2 + 3*Z1, scale = 1)

# Step 3: Generate Z3 | Z1, Z2 ~ Gamma(shape = 2 + 3*(Z2/2), scale = 1)
U3_21 <- runif(sampleSize)
# Z3 <- qnorm(U3_21, mean = Z2, sd = 0.75)
Z3 <- qgamma(U3_21, shape = 2 + 3*(Z2/2), scale = 1)

# U4_321 <- runif(sampleSize)
# # Z4 <- qnorm(U4_321, mean = Z3, sd=0.75)
# Z4 <- qgamma(U4_321, shape = 2 + 3*(Z3/2), scale = 1)

# Combine the samples into a data frame.
# The columns Z1, Z2, Z3 are the observational samples.
# The columns rank_Z1, rank_Z2, rank_Z3 are the underlying U(0,1) draws.
dataBN_norm <- data.frame(Z1 = Z1, Z2 = Z2, Z3 = Z3,
                           rank_Z1 = U1, rank_Z2 = U2_1, rank_Z3 = U3_21)

# We assume the first D-1 columns are the covariates and the Dth column is the outcome.
covariate_data <- dataBN_norm[, 1:D]
# Since the vine simulation returns uniform [0,1] marginals, we can use these as our conditional covariate ranks.
cond_covariate_ranks <- dataBN_norm[, (D+1):(2*D)]

# Define the topological order (here the natural order: 1,2,...,D) and set the vine correlation parameter.
topoOrder <- c(3,1,2)
vine_cor_params <- c(0.5, 0.5, 0.0)

# ------------------------------------------------------------------
# (i) Generate Outcome Rank Samples Using simulateOutcomeSamples
# ------------------------------------------------------------------

sampleResults <- simulateConditionalOutcomeSamples(covariate_data = covariate_data,
                                        cond_covariate_ranks = cond_covariate_ranks,
                                        vine_cor_params = vine_cor_params,
                                        topoOrder = topoOrder)
print(solve(sampleResults$gaussianCopulaFit$correlationMatrix))
print(sampleResults$fullCorrelationMatrix)
print(solve(sampleResults$fullCorrelationMatrix))

# The outcome rank samples generated by conditioning on the covariates:
outcomeRankSamples <- as.vector(sampleResults$outcomeRankSamples)
Y <- qnorm(outcomeRankSamples)

# Scale vectors
Z1 <- scale(Z1)
Z2 <- scale(Z2)
Z3 <- scale(Z3)
Y <- scale(Y)

# # For illustration, plot a histogram of the generated outcome ranks:
# ggplot(data.frame(outcome = outcomeRankSamples), aes(x = outcome)) +
#   geom_histogram(bins = 30, fill = "lightblue", colour = "black") +
#   labs(title = "Histogram of Generated Outcome Rank Samples",
#        x = "Outcome Rank (on [0,1])", y = "Frequency") +
#   theme_minimal()


# ------------------------------------------------------------------
# (ii) Run the Bootstrapped Kendall's Tau Test on Two Chosen Variables
# ------------------------------------------------------------------
set.seed(1)
n_boot = 200
sample_size = 2000

# Ensure the output directory exists
if (!dir.exists("./plots")) {
  dir.create("./plots")
}

custom_theme <- theme_minimal() +
  theme(
    plot.title = element_blank(),
    text = element_text(family = "Helvetica", size = 14),
    axis.title = element_text(face = "bold"),
    panel.grid.major = element_line(color = "white"),
    panel.grid.minor = element_line(color = "white"),
    panel.background = element_rect(fill = "white"),
    plot.background  = element_rect(fill = "white"),
    panel.border = element_blank()
  )

# Testing whether Z1 _|_ Z3 | Z2 using bootstrapped GCM test.
p_values1 <- bootstrappedCondIndTest_GCM(Z1, Z3, Z2, n_boot = n_boot, sample_size = sample_size, verbose = TRUE, regr.method = 'gam')
p1 <- ggplot(data.frame(p_value = p_values1), aes(x = p_value)) +
  geom_histogram(bins = 10, fill = "grey30", colour = "black") +
  labs(x = "p-value", y = "Frequency") +
  scale_x_continuous(limits = c(0, 1)) +
  custom_theme
unif_p1 <- ks.test(p_values1, "punif")



# Save plot 1
ggsave("bootstrapped_gcm_pvalues1.png", plot = p1, path = "./plots", width = 6, height = 4, dpi = 300)

# Testing whether Z1 _|_ Z3 | Z2, Y using bootstrapped GCM test.
p_values2 <- bootstrappedCondIndTest_GCM(Z1, Z3, cbind(Z2, Y), n_boot = n_boot, sample_size = sample_size, verbose = TRUE, regr.method = 'gam')
p2 <- ggplot(data.frame(p_value = p_values2), aes(x = p_value)) +
  geom_histogram(bins = 10, fill = "grey30", colour = "black") +
  labs(x = "p-value", y = "Frequency") +
  scale_x_continuous(limits = c(-1e-1, 1)) +
  custom_theme
unif_p2 <- ks.test(p_values2, "punif")


# Save plot 2
ggsave("bootstrapped_gcm_pvalues2.png", plot = p2, path = "./plots", width = 6, height = 4, dpi = 300)

# Testing whether Z2 _|_ Y | Z1, Z3 using bootstrapped GCM test.
p_values3 <- bootstrappedCondIndTest_GCM(Z2, Y, cbind(Z1, Z3), n_boot = n_boot, sample_size = sample_size, verbose = TRUE, regr.method = 'gam')
p3 <- ggplot(data.frame(p_value = p_values3), aes(x = p_value)) +
  geom_histogram(bins = 10, fill = "grey30", colour = "black") +
  labs(x = "p-value", y = "Frequency") +
  scale_x_continuous(limits = c(0, 1)) +
  custom_theme
unif_p3 <- ks.test(p_values3, "punif")


# Save plot 3
ggsave("bootstrapped_gcm_pvalues3.png", plot = p3, path = "./plots", width = 6, height = 4, dpi = 300)


# Print pvalues
print(unif_p1$p.value)
print(unif_p2$p.value)
print(unif_p3$p.value)
